[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "samplers",
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
